version: '3'

services:
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: ${PRODUCTS_DATASOURCE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${PRODUCTS_DATASOURCE_PASSWORD:-password}
    volumes:
      - products-data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  products-data:
